### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by domenic** [comment]
I don't think this module is platform-dependent, so this isn't necessary.

**Comment by dineshks1** [comment]
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

**Comment by domenic** [comment]
I'm hopeful that the Ubuntu project or the ppc64le project can do their own testing, and not rely on my own Travis CI quota.

**Comment by gerrith3** [comment]
@domenic your Travis CI quota is potentially infinite - they are simply cracking down on bitcoin miners and such which have been using the service.,  If you use up all of your credits, you can put in a request here to get more:  https://support.travis-ci.com/hc/en-us/requests - you may have to make an account there but that is their ticketing system and most likely to get you a predictable response.  You can also email to support@travis-ci.com but that may not be as well tracked.  

BTW, IBM supplies hardware for debian/ubuntu, and other distros but we are trying to consolidate all testing in a single cloud location, which makes travis-ci top-of-tree testing the most cost efficient use of hardware.

**Comment by domenic** [comment]
That's fine. I'm still not interested in supporting your efforts; you need to do that on your own.

**Pull request closed without merging**
